# Site settings
title: ZW Blog
SEOTitle: 志威的博客 | ZW Blog
header-img: img/post-bg-desk.jpg
email: zhiweichen95@126.com
description: "Every failure is leading towards success."
keyword: "ZW, ZW Blog, 志威的博客"
url: "http://zhiwei.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zhiweichen95/zhiwei.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-ZW-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     嘿芝麻
github_username:    zhiweichen95
facebook_username:  zhiweichen
# jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: zhiwei

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 2a6afc1aebed4f877bc8                            #生成的clientID
  clientSecret: f2c94e20908cb8d453f1a68d8e0d180005ba4ca5    #生成的clientSecret
  repo: zhiwei.github.io   #仓库名称
  owner: zhiweichen95    #github用户名
  admin: zhiweichen95
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-136836728-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CSND·嘿芝麻",
        href: "https://blog.csdn.net/zw__chen"
    },{
        title: "GitHub·zhiweichen",
        href: "https://github.com/zhiweichen95"
    }
]
